run:
  timeout: 10m
  tests: false
  skip-dirs:
    - vendor
    - node_modules
    - frontend
    - data
    - grafana
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - deadcode
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gosec
  disable:
    - scopelint
    - exhaustivestruct
    - gochecknoglobals
    - gochecknoinits
    - wsl
    - nlreturn
    - exhaustive
    - wrapcheck
    - thelper
    - ifshort
    - cyclop

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 30
  goconst:
    min-len: 3
    min-occurrences: 3
  dupl:
    threshold: 100
  govet:
    check-shadowing: true
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (io.Writer).Write
      - fmt.Printf
      - fmt.Fprintf

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - linters:
        - gosec
      text: "G[0-9]{3}"
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false