global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "masterchef-bench"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["agent-service:8080"]
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Add Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  # Add PostgreSQL metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  # Add Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # Add Jaeger metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
