# MasterChef-Bench Configuration

# Server settings
port: "8080"
environment: "development"
log_level: "info"

# Database connection
database_url: "sqlite:///./data/escoffier.db"

# OpenAI Configuration
openai:
  api_key: ""  # Set your OpenAI API key here or via OPENAI_API_KEY env var
  model: "gpt-4"
  enabled: false  # Set to true when you have an API key

# Anthropic Configuration
anthropic:
  api_key: ""  # Set your Anthropic API key here or via ANTHROPIC_API_KEY env var
  model: "claude-3-sonnet-20240229"
  enabled: false  # Set to true when you have an API key

# Cohere Configuration
cohere:
  api_key: ""  # Set your Cohere API key here or via COHERE_API_KEY env var
  model: "command-r-plus"
  enabled: false  # Set to true when you have an API key

# GitHub Models Configuration (FREE)
github:
  api_key: ""  # Set your GitHub token here or via GITHUB_TOKEN env var
  model: "gpt-4o-mini"
  enabled: false  # Set to true when you have a GitHub token

# Ollama Configuration (FREE LOCAL)
ollama:
  model: "llama3.2:1b"
  enabled: true  # Set to true when Ollama is running locally

# Hugging Face Configuration (FREE)
huggingface:
  api_key: ""  # Set your HF token here or via HF_TOKEN env var
  model: "cohere/command-r"
  enabled: false  # Set to true when you have an HF token