# MasterChef-Bench Configuration

# Server settings
port: "8080"
environment: "development"
log_level: "info"

# Database connection
# Uses SQLite by default - change path as needed
database_url: "./data/escoffier.db"

# OpenAI Configuration
openai:
  api_key: ""  # Set your OpenAI API key here or via OPENAI_API_KEY env var
  model: "gpt-4"
  base_url: "https://api.openai.com/v1"
  enabled: false  # Set to true when you have an API key

# Cohere Configuration  
cohere:
  api_key: ""  # Set your Cohere API key here or via COHERE_API_KEY env var
  model: "command-r-plus"
  base_url: "https://api.cohere.ai/v1"
  enabled: false  # Set to true when you have an API key

# Anthropic Configuration
anthropic:
  api_key: ""  # Set your Anthropic API key here or via ANTHROPIC_API_KEY env var
  model: "claude-3-sonnet-20240229"
  base_url: "https://api.anthropic.com/v1"
  enabled: false  # Set to true when you have an API key

# Kitchen simulation settings
kitchen:
  max_agents: 10
  simulation_speed: 1.0
  default_stress_level: 0.0
  enable_crisis_events: true

# Metrics collection
metrics:
  collection_interval: 30
  enable_export: true
  export_path: "./data/metrics"