# GitHub Models Configuration for Free Testing
# This configuration uses GitHub Models which provides free access to various LLMs

# API Configuration
api:
  port: 8080
  host: "localhost"
  debug: true

# GitHub Models Configuration
github:
  # Get your GitHub token from: https://github.com/settings/tokens
  # The token needs the 'repo' scope
  token: "${GITHUB_TOKEN}"
  
  # Available models:
  # - gpt-4o (most capable)
  # - gpt-4o-mini (faster, cheaper)
  # - phi-3.5-mini-instruct
  # - meta-llama-3.1-8b-instruct
  # - meta-llama-3.1-70b-instruct
  # - mistral-nemo
  # - cohere-command-r
  model: "gpt-4o-mini"
  
  # API endpoint
  endpoint: "https://models.inference.ai.azure.com"

# Model configuration
model_config:
  temperature: 0.7
  max_tokens: 2048
  provider: "github-models"

# Database Configuration (SQLite for local testing)
database_url: "sqlite://data/escoffier.db"
database_config:
  max_connections: 10
  idle_timeout: "5m"
  max_idle_connections: 5

# Redis Configuration (optional for local testing)
redis:
  enabled: false
  url: "redis://localhost:6379/0"

# Metrics Configuration
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  collection_interval: "10s"

# Logging Configuration
log_level: "debug"
log_format: "text"
log_output: "stdout"

# Agent Configuration (same as main config)
agents:
  executive_chef:
    permissions:
      - menu_planning
      - staff_management
      - inventory_control
      - quality_control
      - kitchen_supervision
    memory_config:
      short_term_capacity: 100
      long_term_ttl: "24h"

  sous_chef:
    stations:
      - hot
      - cold
      - pastry
      - grill
    permissions:
      - order_management
      - staff_supervision
      - quality_control
      - station_management
      - inventory_monitoring
    memory_config:
      short_term_capacity: 50
      long_term_ttl: "12h"

# Kitchen Configuration
kitchen:
  stations:
    hot:
      capacity: 10
      equipment:
        - stove
        - oven
        - grill
        - fryer
    cold:
      capacity: 8
      equipment:
        - refrigerator
        - prep_table
        - mixer
    pastry:
      capacity: 6
      equipment:
        - mixer
        - oven
        - refrigerator
    grill:
      capacity: 8
      equipment:
        - grill
        - smoker
        - prep_table

# Evaluation Configuration
evaluation:
  metrics:
    role_coherence:
      weight: 0.4
      threshold: 0.8
    task_completion:
      weight: 0.3
      threshold: 0.75
    coordination:
      weight: 0.3
      threshold: 0.7
  collection_interval: "1m"
  report_interval: "1h"

# Memory System Configuration
memory:
  vector_store:
    engine: "memory"  # In-memory for testing
    dimension: 1536
    similarity_threshold: 0.8
  cache:
    type: "memory"
    ttl: "1h"
    max_size: "100MB"